### ISSUE TITLE
Invalid wallet ID in entrance/push

### ISSUE THREAD

**Issue by yegor256** [zerocracy/zold#65]
```
Invalid wallet ID '1'
	/app/lib/zold/id.rb:32:in `initialize'
	/app/lib/zold/commands/push.rb:52:in `new'
	/app/lib/zold/commands/push.rb:52:in `block in run'
	/app/lib/zold/commands/push.rb:51:in `each'
	/app/lib/zold/commands/push.rb:51:in `run'
	/app/lib/zold/node/entrance.rb:84:in `block in push_unsafe'
	/app/lib/zold/node/entrance.rb:81:in `each'
	/app/lib/zold/node/entrance.rb:81:in `push_unsafe'
	/app/lib/zold/node/entrance.rb:52:in `block in push'
	/app/lib/zold/node/entrance.rb:51:in `synchronize'
	/app/lib/zold/node/entrance.rb:51:in `push'
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@2b7a3737-162c-475c-82b8-037c82174a7a, thread: pool-7-thread-1
com.zerocracy.pm.Claims[112] java.lang.IllegalStateException: Duplicate claims are not allowed in [C91QJT4CF](https://www.0crat.com/p/C91QJT4CF), can't add this XML to 3 existing ones (org.cactoos.collection.Sorted@66c47fd2):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1471035021">
   <created>2018-05-27T10:35:42.566Z</created>
   <type>Request order start</type>
   <token>github;zerocracy/zold;65</token>
   <author>yegor256</author>
   <params>
      <param name="login">yegor256</param>
      <param name="job">gh:zerocracy/zold#65</param>
      <param name="reason">GitHub issue was assigned by @yegor256[/z](https://www.0crat.com/u/yegor256)</param>
   </params>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: zerocracy/zold#65, Action: `assigned`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@2b7a3737-162c-475c-82b8-037c82174a7a, thread: pool-6-thread-1
com.zerocracy.pm.Claims[112] java.lang.IllegalStateException: Duplicate claims are not allowed in [C91QJT4CF](https://www.0crat.com/p/C91QJT4CF), can't add this XML to 5 existing ones (org.cactoos.collection.Sorted@6b312fcb):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1471035035">
   <created>2018-05-27T10:35:49.545Z</created>
   <type>Request order start</type>
   <token>github;zerocracy/zold;65</token>
   <author>yegor256</author>
   <params>
      <param name="login">yegor256</param>
      <param name="job">gh:zerocracy/zold#65</param>
      <param name="reason">GitHub issue was assigned by @yegor256[/z](https://www.0crat.com/u/yegor256)</param>
   </params>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: zerocracy/zold#65, Action: `assigned`

**Comment by 0crat** [comment]
The job [#65](https://github.com/zerocracy/zold/issues/65) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C91QJT4CF/1471036108); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)com.zerocracy.Par@3535bbf4

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.2`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@4702e99b-d092-49d6-9d29-5cfdf189dcbd, thread: pool-18-thread-1
com.zerocracy.pm.Claims[113] java.lang.IllegalStateException: Duplicate claims are not allowed in [C91QJT4CF](https://www.0crat.com/p/C91QJT4CF), can't add this XML to 2 existing ones (org.cactoos.text.JoinedText@49aeeca9):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1471115062">
   <created>2018-05-27T11:15:35.069Z</created>
   <type>Close job</type>
   <token>github;zerocracy/zold;65</token>
   <author>yegor256</author>
   <params>
      <param name="job">gh:zerocracy/zold#65</param>
      <param name="reason">GitHub issue was closed</param>
   </params>
   <until>2018-05-27T11:30:35.071Z</until>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: zerocracy/zold#65, Action: `closed`

**Comment by 0crat** [comment]
Job `gh:zerocracy/zold#65` is not assigned, can't get start time

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#65](https://github.com/zerocracy/zold/issues/65) is now out of scope
