### ISSUE TITLE
keep recent copy in "copies"

### ISSUE THREAD

**Issue by yegor256** [zerocracy/zold#74]
Let's keep recently stable version of the wallet in `copies`. When we merge, we save it. When we push, we save it. Then, when we do `show` -- we can see which one is still not pushed to the net.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6a151509-d0d4-40fa-a569-53d8cdf9ca67, thread: pool-567-thread-1
com.zerocracy.pm.Claims[113] java.lang.IllegalStateException: Duplicate claims are not allowed in [C91QJT4CF](https://www.0crat.com/p/C91QJT4CF), can't add this XML to 4 existing ones (Close job;{job=gh:zerocracy/zold#73, reason=GitHub issue was closed},Close job;{job=gh:zerocracy/zold#73, reason=GitHub issue was closed},Ping;{},Request order start;{login=yegor256, job=gh:zerocracy/zold#74, reason=GitHub issue was assigned by @yegor256[/z](https://www.0crat.com/u/yegor256)}):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1471821703">
   <created>2018-05-27T18:10:42.392Z</created>
   <type>Request order start</type>
   <token>github;zerocracy/zold;74</token>
   <author>yegor256</author>
   <params>
      <param name="login">yegor256</param>
      <param name="job">gh:zerocracy/zold#74</param>
      <param name="reason">GitHub issue was assigned by @yegor256[/z](https://www.0crat.com/u/yegor256)</param>
   </params>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: zerocracy/zold#74, Action: `assigned`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6a151509-d0d4-40fa-a569-53d8cdf9ca67, thread: pool-566-thread-1
com.zerocracy.pm.Claims[113] java.lang.IllegalStateException: Duplicate claims are not allowed in [C91QJT4CF](https://www.0crat.com/p/C91QJT4CF), can't add this XML to 6 existing ones (Close job;{job=gh:zerocracy/zold#73, reason=GitHub issue was closed},Close job;{job=gh:zerocracy/zold#73, reason=GitHub issue was closed},Error;{reason=GitHub issue was assigned by @yegor256[/z](https://www.0crat.com/u/yegor256), stacktrace=java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/request_order_start.groovy
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:125)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:81)
	at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:66)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:64)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
	at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.scalar.NumberEnvelope.doubleValue(NumberEnvelope.java:113)
	at org.cactoos.iterable.LengthOf.lambda$new$0(LengthOf.java:51)
	at org.cactoos.scalar.NumberEnvelope.lambda$new$1(NumberEnvelope.java:73)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.scalar.NumberEnvelope.intValue(NumberEnvelope.java:98)
	at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:67)
	at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:37)
	at org.cactoos.func.IoCheckedBiFunc.lambda$apply$0(IoCheckedBiFunc.java:60)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:61)
	at com.zerocracy.farm.reactive.DefaultFlush.process(DefaultFlush.java:98)
	at com.zerocracy.farm.reactive.DefaultFlush.lambda$exec$0(DefaultFlush.java:67)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:59)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:59)
	at org.cactoos.func.IoCheckedProc.exec(IoCheckedProc.java:57)
	at com.zerocracy.pm.Claims.take(Claims.java:150)
	at com.zerocracy.farm.reactive.DefaultFlush.exec(DefaultFlush.java:66)
	at com.zerocracy.farm.reactive.DefaultFlush.exec(DefaultFlush.java:44)
	at com.zerocracy.farm.reactive.AsyncFlush.lambda$exec$2(AsyncFlush.java:118)
	at com.jcabi.log.VerboseCallable.call(VerboseCallable.java:173)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:221)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:115)
	... 41 more
Caused by: java.lang.IllegalStateException: Duplicate claims are not allowed in [C91QJT4CF](https://www.0crat.com/p/C91QJT4CF), can't add this XML to 4 existing ones (Close job;{job=gh:zerocracy/zold#73, reason=GitHub issue was closed},Close job;{job=gh:zerocracy/zold#73, reason=GitHub issue was closed},Job was added to WBS;{cause=1471821703, reason=Order start requested, but WBS is empty, login=yegor256, job=gh:zerocracy/zold#74, flow=Request order start},Request order start;{login=yegor256, job=gh:zerocracy/zold#74, reason=GitHub issue was assigned by @yegor256[/z](https://www.0crat.com/u/yegor256)[/z](https://www.0crat.com/u/yegor256)}):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1471821704">
   <created>2018-05-27T18:10:46.496Z</created>
   <token>github;zerocracy/zold;74</token>
   <params>
      <param name="login">yegor256</param>
      <param name="job">gh:zerocracy/zold#74</param>
      <param name="cause">1471821703</param>
      <param name="flow">Request order start</param>
      <param name="reason">Order start requested, but WBS is empty</param>
   </params>
   <type>Job was added to WBS</type>
</claim>

	at com.zerocracy.pm.Claims.add(Claims.java:113)
	at com.zerocracy.pm.Claims.add(Claims.java:82)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:105)
	at com.zerocracy.pm.ClaimOut$postTo$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at com.zerocracy.stk.pm.in.orders.request_order_start.exec(request_order_start.groovy:38)
	... 46 more
, cause=1471821703, origin_id=1471821703, login=yegor256, job=gh:zerocracy/zold#74, message=Claim #1471821703 in [C91QJT4CF](https://www.0crat.com/p/C91QJT4CF): type="Request order start", stakeholder="com/zerocracy/stk/pm/in/orders/request_order_start.groovy", author="yegor256", token="github;zerocracy/zold;74", flow=Request order start, origin_type=Request order start},Error;{reason=Order start requested, but WBS is empty, stacktrace=java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/cost/pay_per_github_bug.groovy
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:125)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:81)
	at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:66)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:64)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
	at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.scalar.NumberEnvelope.doubleValue(NumberEnvelope.java:113)
	at org.cactoos.iterable.LengthOf.lambda$new$0(LengthOf.java:51)
	at org.cactoos.scalar.NumberEnvelope.lambda$new$1(NumberEnvelope.java:73)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.scalar.NumberEnvelope.intValue(NumberEnvelope.java:98)
	at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:67)
	at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:37)
	at org.cactoos.func.IoCheckedBiFunc.lambda$apply$0(IoCheckedBiFunc.java:60)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:61)
	at com.zerocracy.farm.reactive.DefaultFlush.process(DefaultFlush.java:98)
	at com.zerocracy.farm.reactive.DefaultFlush.lambda$exec$0(DefaultFlush.java:67)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:59)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:59)
	at org.cactoos.func.IoCheckedProc.exec(IoCheckedProc.java:57)
	at com.zerocracy.pm.Claims.take(Claims.java:150)
	at com.zerocracy.farm.reactive.DefaultFlush.exec(DefaultFlush.java:66)
	at com.zerocracy.farm.reactive.DefaultFlush.exec(DefaultFlush.java:44)
	at com.zerocracy.farm.reactive.AsyncFlush.lambda$exec$2(AsyncFlush.java:118)
	at com.jcabi.log.VerboseCallable.call(VerboseCallable.java:173)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:221)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:115)
	... 41 more
Caused by: java.lang.IllegalStateException: Duplicate claims are not allowed in [C91QJT4CF](https://www.0crat.com/p/C91QJT4CF), can't add this XML to 5 existing ones (Close job;{job=gh:zerocracy/zold#73, reason=GitHub issue was closed},Close job;{job=gh:zerocracy/zold#73, reason=GitHub issue was closed},Error;{reason=GitHub issue was assigned by @yegor256[/z](https://www.0crat.com/u/yegor256)[/z](https://www.0crat.com/u/yegor256), stacktrace=java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/request_order_start.groovy
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:125)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:81)
	at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:66)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:64)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
	at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.scalar.NumberEnvelope.doubleValue(NumberEnvelope.java:113)
	at org.cactoos.iterable.LengthOf.lambda$new$0(LengthOf.java:51)
	at org.cactoos.scalar.NumberEnvelope.lambda$new$1(NumberEnvelope.java:73)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.scalar.NumberEnvelope.intValue(NumberEnvelope.java:98)
	at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:67)
	at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:37)
	at org.cactoos.func.IoCheckedBiFunc.lambda$apply$0(IoCheckedBiFunc.java:60)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:61)
	at com.zerocracy.farm.reactive.DefaultFlush.process(DefaultFlush.java:98)
	at com.zerocracy.farm.reactive.DefaultFlush.lambda$exec$0(DefaultFlush.java:67)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:59)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:59)
	at org.cactoos.func.IoCheckedProc.exec(IoCheckedProc.java:57)
	at com.zerocracy.pm.Claims.take(Claims.java:150)
	at com.zerocracy.farm.reactive.DefaultFlush.exec(DefaultFlush.java:66)
	at com.zerocracy.farm.reactive.DefaultFlush.exec(DefaultFlush.java:44)
	at com.zerocracy.farm.reactive.AsyncFlush.lambda$exec$2(AsyncFlush.java:118)
	at com.jcabi.log.VerboseCallable.call(VerboseCallable.java:173)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:221)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:115)
	... 41 more
Caused by: java.lang.IllegalStateException: Duplicate claims are not allowed in [C91QJT4CF](https://www.0crat.com/p/C91QJT4CF), can't add this XML to 4 existing ones (Close job;{job=gh:zerocracy/zold#73, reason=GitHub issue was closed},Close job;{job=gh:zerocracy/zold#73, reason=GitHub issue was closed},Job was added to WBS;{cause=1471821703, reason=Order start requested, but WBS is empty, login=yegor256, job=gh:zerocracy/zold#74, flow=Request order start},Request order start;{login=yegor256, job=gh:zerocracy/zold#74, reason=GitHub issue was assigned by @yegor256[/z](https://www.0crat.com/u/yegor256)[/z](https://www.0crat.com/u/yegor256)[/z](https://www.0crat.com/u/yegor256)}):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1471821704">
   <created>2018-05-27T18:10:46.496Z</created>
   <token>github;zerocracy/zold;74</token>
   <params>
      <param name="login">yegor256</param>
      <param name="job">gh:zerocracy/zold#74</param>
      <param name="cause">1471821703</param>
      <param name="flow">Request order start</param>
      <param name="reason">Order start requested, but WBS is empty</param>
   </params>
   <type>Job was added to WBS</type>
</claim>

	at com.zerocracy.pm.Claims.add(Claims.java:113)
	at com.zerocracy.pm.Claims.add(Claims.java:82)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:105)
	at com.zerocracy.pm.ClaimOut$postTo$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at com.zerocracy.stk.pm.in.orders.request_order_start.exec(request_order_start.groovy:38)
	... 46 more
, cause=1471821703, origin_id=1471821703, login=yegor256, job=gh:zerocracy/zold#74, message=Claim #1471821703 in [C91QJT4CF](https://www.0crat.com/p/C91QJT4CF): type="Request order start", stakeholder="com/zerocracy/stk/pm/in/orders/request_order_start.groovy", author="yegor256", token="github;zerocracy/zold;74", flow=Request order start, origin_type=Request order start},Job was added to WBS;{cause=1471821703, reason=Order start requested, but WBS is empty, login=yegor256, job=gh:zerocracy/zold#74, flow=Request order start},Make payment;{cause=1471821704, reason=Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29), job=gh:zerocracy/zold#74, login=yegor256, flow=Request order start; Job was added to WBS, minutes=15}):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1471821706">
   <created>2018-05-27T18:10:47.636Z</created>
   <token>github;zerocracy/zold;74</token>
   <params>
      <param name="job">gh:zerocracy/zold#74</param>
      <param name="cause">1471821704</param>
      <param name="flow">Request order start; Job was added to WBS</param>
      <param name="login">yegor256</param>
      <param name="reason">Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29)</param>
      <param name="minutes">15</param>
   </params>
   <type>Make payment</type>
</claim>

	at com.zerocracy.pm.Claims.add(Claims.java:113)
	at com.zerocracy.pm.Claims.add(Claims.java:82)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:105)
	at com.zerocracy.pm.ClaimOut$postTo$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at com.zerocracy.stk.pm.cost.pay_per_github_bug.exec(pay_per_github_bug.groovy:53)
	... 46 more
, cause=1471821704, origin_id=1471821704, login=yegor256, job=gh:zerocracy/zold#74, message=Claim #1471821704 in [C91QJT4CF](https://www.0crat.com/p/C91QJT4CF): type="Job was added to WBS", stakeholder="com/zerocracy/stk/pm/cost/pay_per_github_bug.groovy", token="github;zerocracy/zold;74", flow=Request order start; Job was added to WBS, origin_type=Job was added to WBS},Make payment;{cause=1471821704, reason=Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29), job=gh:zerocracy/zold#74, login=yegor256, flow=Request order start; Job was added to WBS, minutes=15},Request order start;{login=yegor256, job=gh:zerocracy/zold#74, reason=GitHub issue was assigned by @yegor256[/z](https://www.0crat.com/u/yegor256)}):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1471821708">
   <created>2018-05-27T18:10:48.427Z</created>
   <type>Request order start</type>
   <token>github;zerocracy/zold;74</token>
   <author>yegor256</author>
   <params>
      <param name="login">yegor256</param>
      <param name="job">gh:zerocracy/zold#74</param>
      <param name="reason">GitHub issue was assigned by @yegor256[/z](https://www.0crat.com/u/yegor256)</param>
   </params>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: zerocracy/zold#74, Action: `assigned`

**Comment by 0crat** [comment]
The job [#74](https://github.com/zerocracy/zold/issues/74) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C91QJT4CF/1471821711); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)com.zerocracy.Par@20fb2bdd

**Comment by yegor256** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/zold/issues/74#issuecomment-392445016))

@yegor256 Job [#74](https://github.com/yegor256/zold/issues/74) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/zold/issues/74#issuecomment-392445016))

@yegor256 The job [#74](https://github.com/yegor256/zold/issues/74) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C91QJT4CF/1480772939); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)com.zerocracy.Par@15be73f1

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@c1247f40-4c56-45a0-880c-9418d4621a65, thread: pool-288-thread-1
java.lang.Thread[-2] java.lang.OutOfMemoryError: unable to create new native thread
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: zold-io/zold#74, Action: `assigned`
